In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("Array using numpy is:-", arr1)
print("\n")
print("Addition of 2 in all the element:-", arr1 + 2)
print("\n")
print("Multiplication of 3 in all the element:-", arr1 * 3)
print("\n")
print("Division of 2 in all the element:-", arr1 / 2)


Array using numpy is:- [1 2 3 4 5]


Addition of 2 in all the element:- [3 4 5 6 7]


Multiplication of 3 in all the element:- [ 3  6  9 12 15]


Division of 2 in all the element:- [0.5 1.  1.5 2.  2.5]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed array is: ", arr[::-1])

Reversed array is:  [5 4 6 3 2 1]


In [30]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1])
mfvx = np.bincount(x).argmax()
indicesx = np.where(x == mfvx)
print("Most frequent value in x: ", mfvx)
print("There indices are: ", indicesx[0])

Most frequent value in x:  1
There indices are:  [0 5 7 8]


In [32]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
mfvy = np.bincount(y).argmax()
indicesy = np.where(y == mfvy)
print("Most frequent value in x: ", mfvy)
print("There indices are: ", indicesy[0])


Most frequent value in x:  1
There indices are:  [0 1 2]


In [47]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("The given array is: \n", arr)
print("\n")
print("Accesing first row and second column: ", arr[0][1])
ind1 = np.where(arr == arr[0][1])
print("It is at index: ", ind1)
print("\n")
ind2 = np.where(arr == arr[2][0])
print("Accesing third row and first column: ", arr[2][0])
print("It is at index: ", ind2)


The given array is: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


Accesing first row and second column:  20
It is at index:  (array([0]), array([1]))


Accesing third row and first column:  70
It is at index:  (array([2]), array([0]))


In [1]:
import numpy as np

Sourav = np.linspace(10, 100, 25)
print("Sourav = ", Sourav)
print("\n")
print("Shape: ", Sourav.shape)
print("\n")
print("Dimension: ", Sourav.ndim)
print("\n")
print("Total Shape: ", Sourav.size)
print("\n")
print("Data Type: ", Sourav.dtype)
print("\n")
print("Total Bytes: ", Sourav.nbytes)


Sourav =  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Shape:  (25,)


Dimension:  1


Total Shape:  25


Data Type:  float64


Total Bytes:  200


In [2]:
print("Reshaped array: ", Sourav.reshape(25, 1))

Reshaped array:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [3]:
print("Transpose using T?")
print(Sourav.T)
print("No because, T attribute doesn't works in 1d arrays")

try:
    transposed_array = Sourav.T
except AttributeError as e:
    print("Error", e)

Transpose using T?
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
No because, T attribute doesn't works in 1d arrays


In [4]:
import numpy as np

ucs420_Sourav = np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]])
print("ucs420_Sourav = \n", ucs420_Sourav)
print('\n')
print('Mean: ', np.mean(ucs420_Sourav))
print('\n')
print('Median: ', np.median(ucs420_Sourav))
print('\n')
print('Min: ', np.min(ucs420_Sourav))
print('\n')
print('Max: ', np.max(ucs420_Sourav))
print('\n')
print('Unique elements: ', np.unique(ucs420_Sourav))
print('\n')

ucs420_Sourav = 
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


Mean:  43.333333333333336


Median:  37.5


Min:  10


Max:  90


Unique elements:  [10 15 20 30 35 40 50 60 70 80 90]




In [5]:
reshaped_ucs420_Sourav = ucs420_Sourav.reshape(4, 3)
print("reshaped_ucs420_Sourav = \n", reshaped_ucs420_Sourav)
print("\n")
resized_ucs420_Sourav = ucs420_Sourav[:2, :3]
print("resized_ucs420_Sourav = \n", resized_ucs420_Sourav)

reshaped_ucs420_Sourav = 
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


resized_ucs420_Sourav = 
 [[10 20 30]
 [50 60 70]]
